name: Label Codex PRs
on:
  pull_request_target:
    types: [opened, reopened]
permissions:
  pull-requests: write
jobs:
  label:
    if: startsWith(github.event.pull_request.head.ref, 'codex/')
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
